In [17]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import Normalizer
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
import pandas as pd
import io
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_regression
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import Ridge
from sklearn.svm import SVR
from sklearn.experimental import enable_hist_gradient_boosting 
from sklearn.ensemble import HistGradientBoostingRegressor
from sklearn.ensemble import GradientBoostingRegressor

In [18]:
diamonds = pd.read_csv('../input/data.csv')
test = pd.read_csv('../input/test.csv')

In [19]:
diamonds.head()

   carat        cut color clarity  depth  table     x     y     z  price
0   2.26      Ideal     G     SI2   61.9   57.0  8.44  8.36  5.20  12831
1   2.43  Very Good     H     SI2   63.2   57.0  8.56  8.50  5.39  16170
2   0.80    Premium     F     SI2   61.0   57.0  6.03  6.01  3.67   2797
3   0.40      Ideal     F      I1   63.3   60.0  4.68  4.64  2.95    630
4   0.31      Ideal     G     VS2   61.6   55.0  4.39  4.37  2.70    698

In [20]:
def cutOrdinal(a):
    if a == 'Fair':
        return 1
    elif a == 'Good':
        return 2
    elif a == 'Very Good':
        return 3
    elif a == 'Premium':
        return 4
    else:
        return 5

In [21]:
def colorOrdinal(a):
    if a == 'J':
        return 1
    elif a == 'I':
        return 2
    elif a == 'H':
        return 3
    elif a == 'G':
        return 4
    elif a == 'F':
        return 5
    elif a == 'E':
        return 6
    else:
        return 7

In [22]:
def clarityOrdinal(a):
    if a == 'I1':
        return 1
    elif a == 'SI2':
        return 2
    elif a == 'SI1':
        return 3
    elif a == 'VS2':
        return 4
    elif a == 'VS1':
        return 5
    elif a == 'VVS2':
        return 6
    elif a == 'VVS1':
        return 7
    else:
        return 8

In [23]:
diamonds['cut'] = diamonds['cut'].apply(cutOrdinal)
diamonds['color'] = diamonds['color'].apply(colorOrdinal)
diamonds['clarity'] = diamonds['clarity'].apply(clarityOrdinal)

In [24]:
diamonds.head()

   carat  cut  color  clarity  depth  table     x     y     z  price
0   2.26    5      4        2   61.9   57.0  8.44  8.36  5.20  12831
1   2.43    3      3        2   63.2   57.0  8.56  8.50  5.39  16170
2   0.80    4      5        2   61.0   57.0  6.03  6.01  3.67   2797
3   0.40    5      5        1   63.3   60.0  4.68  4.64  2.95    630
4   0.31    5      4        4   61.6   55.0  4.39  4.37  2.70    698

In [25]:
corrMatrix = diamonds.corr()
corrMatrix.style.background_gradient(cmap='coolwarm').set_precision(2)

In [26]:
columns = ['carat', 'depth', 'table']
for col in columns:
    mean = np.mean(diamonds[col])
    std = np.std(diamonds[col])
    diamonds[col] = (diamonds[col] - mean) / std 

diamonds.head()

      carat  cut  color  clarity     depth     table     x     y     z  price
0  3.081321    5      4        2  0.106170 -0.205764  8.44  8.36  5.20  12831
1  3.439708    3      3        2  1.013798 -0.205764  8.56  8.50  5.39  16170
2  0.003405    4      5        2 -0.522188 -0.205764  6.03  6.01  3.67   2797
3 -0.839859    5      5        1  1.083616  1.138849  4.68  4.64  2.95    630
4 -1.029593    5      4        4 -0.103283 -1.102173  4.39  4.37  2.70    698

In [27]:
'''upper = corrMatrix.where(np.triu(np.ones(corrMatrix.shape), k=1).astype(np.bool))
to_drop = [column for column in upper.columns if any(upper[column] > 0.97)]
to_drop'''

'upper = corrMatrix.where(np.triu(np.ones(corrMatrix.shape), k=1).astype(np.bool))\nto_drop = [column for column in upper.columns if any(upper[column] > 0.97)]\nto_drop'

In [28]:
diamonds = diamonds.drop(['x', 'y', 'z'], axis=1)
diamonds.head()

      carat  cut  color  clarity     depth     table  price
0  3.081321    5      4        2  0.106170 -0.205764  12831
1  3.439708    3      3        2  1.013798 -0.205764  16170
2  0.003405    4      5        2 -0.522188 -0.205764   2797
3 -0.839859    5      5        1  1.083616  1.138849    630
4 -1.029593    5      4        4 -0.103283 -1.102173    698

In [29]:
X = diamonds[['carat', 'cut', 'color', 'clarity', 'depth', 'table']]
y = diamonds['price']

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [31]:
models = {
    #"svm": LinearSVC(),
    #"logistic": LogisticRegression(solver='lbfgs', max_iter=2000),
    #"forest": RandomForestRegressor(),
    #"ridge": Ridge(),
    "svr": SVR(C=1.0, epsilon=0.2),
    #'hist': HistGradientBoostingRegressor(),
    #'gb': GradientBoostingRegressor()
}

for modelName, model in models.items():
    print(f"Training model: {modelName}")
    model.fit(X_train, y_train)
    print(f"Training finished: {modelName}")

Training model: svr

/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

Training finished: svr

In [32]:

scores = cross_val_score(models['svr'], X_train, y_train, scoring='r2', n_jobs=2)
name = str(models['svr'])

print(f'{name}: Average R-Squared Score:', np.mean(scores))

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.2,
    gamma='auto_deprecated', kernel='rbf', max_iter=-1, shrinking=True,
    tol=0.001, verbose=False): Average R-Squared Score: 0.0961363605409

In [33]:
'''from sklearn.metrics import mean_squared_error
from math import sqrt
rmse = sqrt(mean_squared_error(y_test, 'forest'))'''

"from sklearn.metrics import mean_squared_error\nfrom math import sqrt\nrmse = sqrt(mean_squared_error(y_test, 'forest'))"

In [34]:
test.head()

   id  carat      cut color clarity  depth  table     x     y     z
0   0   0.56    Ideal     I     VS2   62.1   54.0  5.30  5.33  3.30
1   1   1.05    Ideal     G     VS2   61.9   56.0  6.56  6.52  4.05
2   2   0.50  Premium     E     VS2   61.5   56.0  5.11  5.07  3.13
3   3   0.80    Ideal     F     VS1   62.8   56.0  5.91  5.96  3.73
4   4   0.54    Ideal     G     VS1   61.4   57.0  5.23  5.20  3.20

In [35]:
test['cut'] = test['cut'].apply(cutOrdinal)
test['color'] = test['color'].apply(colorOrdinal)
test['clarity'] = test['clarity'].apply(clarityOrdinal)
test.head()

   id  carat  cut  color  clarity  depth  table     x     y     z
0   0   0.56    5      2        4   62.1   54.0  5.30  5.33  3.30
1   1   1.05    5      4        4   61.9   56.0  6.56  6.52  4.05
2   2   0.50    4      6        4   61.5   56.0  5.11  5.07  3.13
3   3   0.80    5      5        5   62.8   56.0  5.91  5.96  3.73
4   4   0.54    5      4        5   61.4   57.0  5.23  5.20  3.20

In [36]:
columns = ['carat', 'depth', 'table']
for col in columns:
    mean = np.mean(test[col])
    std = np.std(test[col])
    test[col] = (test[col] - mean) / std 

test.head()

   id     carat  cut  color  clarity     depth     table     x     y     z
0   0 -0.500241    5      2        4  0.241489 -1.537773  5.30  5.33  3.30
1   1  0.535739    5      4        4  0.101972 -0.646693  6.56  6.52  4.05
2   2 -0.627096    4      6        4 -0.177064 -0.646693  5.11  5.07  3.13
3   3  0.007178    5      5        5  0.729801 -0.646693  5.91  5.96  3.73
4   4 -0.542526    5      4        5 -0.246823 -0.201152  5.23  5.20  3.20

In [37]:

d1 = {modelName:model.predict(test[["carat", "cut", "color", "clarity", "depth", "table"]]) for modelName, model in models.items()}

df1 = pd.DataFrame(d1)
df1['id']=test['id']
new = df1[['id','svr']]
new.rename(columns={"svr": "price"}, inplace=True)
new.head()

   id        price
0   0  2358.834463
1   1  3646.068433
2   2  1551.199866
3   3  2481.912109
4   4  1797.542863

In [38]:
new.to_csv('../output/svr.csv', index=False)